#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Aci.Flex.Plugins.AnsellAfe.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/AfeCapture/Form.cshtml")]
    public partial class _Views_AfeCapture_Form_cshtml : System.Web.Mvc.WebViewPage<Aci.Flex.Plugins.AnsellAfe.Web.Models.AfeInitializationData>
    {
        public _Views_AfeCapture_Form_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\AfeCapture\Form.cshtml"
  
    Layout = "~/Views/Shared/_AfeLayout.cshtml";
#if DEBUG
        ;

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 157), Tuple.Create("\"", 202)
            
            #line 7 "..\..\Views\AfeCapture\Form.cshtml"
, Tuple.Create(Tuple.Create("", 163), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/Enum.js?v=1.0")
            
            #line default
            #line hidden
, 163), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 226), Tuple.Create("\"", 284)
            
            #line 8 "..\..\Views\AfeCapture\Form.cshtml"
, Tuple.Create(Tuple.Create("", 232), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/TypeScriptClasses.js?v=1.0")
            
            #line default
            #line hidden
, 232), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 308), Tuple.Create("\"", 362)
            
            #line 9 "..\..\Views\AfeCapture\Form.cshtml"
, Tuple.Create(Tuple.Create("", 314), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/common-helper.js?v=1.0")
            
            #line default
            #line hidden
, 314), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 386), Tuple.Create("\"", 449)
            
            #line 10 "..\..\Views\AfeCapture\Form.cshtml"
, Tuple.Create(Tuple.Create("", 392), Tuple.Create<System.Object, System.Int32>(Url.Content("~/CodeGen/CommonAfeApiController.js?v=1.0")
            
            #line default
            #line hidden
, 392), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 473), Tuple.Create("\"", 534)
            
            #line 11 "..\..\Views\AfeCapture\Form.cshtml"
, Tuple.Create(Tuple.Create("", 479), Tuple.Create<System.Object, System.Int32>(Url.Content("~/CodeGen/SaveAfeApiController.js?v=1.0")
            
            #line default
            #line hidden
, 479), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 558), Tuple.Create("\"", 625)
            
            #line 12 "..\..\Views\AfeCapture\Form.cshtml"
, Tuple.Create(Tuple.Create("", 564), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/AfeCapture/afecapture-form.js?v=1.0")
            
            #line default
            #line hidden
, 564), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 649), Tuple.Create("\"", 700)
            
            #line 13 "..\..\Views\AfeCapture\Form.cshtml"
, Tuple.Create(Tuple.Create("", 655), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/money-view.js?v=1.0")
            
            #line default
            #line hidden
, 655), false)
);

WriteLiteral("></script>\r\n");

            
            #line 14 "..\..\Views\AfeCapture\Form.cshtml"
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\AfeCapture\Form.cshtml"
                                                                                       

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 813), Tuple.Create("\"", 872)
            
            #line 15 "..\..\Views\AfeCapture\Form.cshtml"
, Tuple.Create(Tuple.Create("", 819), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/select-list-helper.js?v=1.0")
            
            #line default
            #line hidden
, 819), false)
);

WriteLiteral("></script>\r\n");

            
            #line 16 "..\..\Views\AfeCapture\Form.cshtml"
#else
    ;

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 910), Tuple.Create("\"", 1004)
            
            #line 18 "..\..\Views\AfeCapture\Form.cshtml"
, Tuple.Create(Tuple.Create("", 916), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/Scripts/Aci.Flex.Plugins.AnsellAfe.Web.Scripts.Enum.js?v=1.0")
            
            #line default
            #line hidden
, 916), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1028), Tuple.Create("\"", 1135)
            
            #line 19 "..\..\Views\AfeCapture\Form.cshtml"
, Tuple.Create(Tuple.Create("", 1034), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/Scripts/Aci.Flex.Plugins.AnsellAfe.Web.Scripts.TypeScriptClasses.js?v=1.0")
            
            #line default
            #line hidden
, 1034), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1159), Tuple.Create("\"", 1262)
            
            #line 20 "..\..\Views\AfeCapture\Form.cshtml"
, Tuple.Create(Tuple.Create("", 1165), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/Scripts/Aci.Flex.Plugins.AnsellAfe.Web.Scripts.common-helper.js?v=1.0")
            
            #line default
            #line hidden
, 1165), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1286), Tuple.Create("\"", 1398)
            
            #line 21 "..\..\Views\AfeCapture\Form.cshtml"
, Tuple.Create(Tuple.Create("", 1292), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/CodeGen/Aci.Flex.Plugins.AnsellAfe.Web.CodeGen.CommonAfeApiController.js?v=1.0")
            
            #line default
            #line hidden
, 1292), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1422), Tuple.Create("\"", 1532)
            
            #line 22 "..\..\Views\AfeCapture\Form.cshtml"
, Tuple.Create(Tuple.Create("", 1428), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/CodeGen/Aci.Flex.Plugins.AnsellAfe.Web.CodeGen.SaveAfeApiController.js?v=1.0")
            
            #line default
            #line hidden
, 1428), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1556), Tuple.Create("\"", 1672)
            
            #line 23 "..\..\Views\AfeCapture\Form.cshtml"
, Tuple.Create(Tuple.Create("", 1562), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/Scripts/Aci.Flex.Plugins.AnsellAfe.Web.Scripts.AfeCapture.afecapture-form.js?v=1.0")
            
            #line default
            #line hidden
, 1562), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1696), Tuple.Create("\"", 1796)
            
            #line 24 "..\..\Views\AfeCapture\Form.cshtml"
, Tuple.Create(Tuple.Create("", 1702), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/Scripts/Aci.Flex.Plugins.AnsellAfe.Web.Scripts.money-view.js?v=1.0")
            
            #line default
            #line hidden
, 1702), false)
);

WriteLiteral("></script>\r\n");

            
            #line 25 "..\..\Views\AfeCapture\Form.cshtml"
    
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\AfeCapture\Form.cshtml"
                                                                                                                                        

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1958), Tuple.Create("\"", 2066)
            
            #line 26 "..\..\Views\AfeCapture\Form.cshtml"
, Tuple.Create(Tuple.Create("", 1964), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/Scripts/Aci.Flex.Plugins.AnsellAfe.Web.Scripts.select-list-helper.js?v=1.0")
            
            #line default
            #line hidden
, 1964), false)
);

WriteLiteral("></script>\r\n");

            
            #line 27 "..\..\Views\AfeCapture\Form.cshtml"
    
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\AfeCapture\Form.cshtml"
Write(Scripts.Render("~/bundles/wysiwyg"));

            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\AfeCapture\Form.cshtml"
                                        
#endif

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"afe-capture-container\"");

WriteLiteral(">\r\n\r\n    <!-- 1. ACE Request Information -->\r\n    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>ACE Request Information</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row col-md-6\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Creation Date</label>\r\n                                    <div");

WriteLiteral(" class=\"data-value col-md-8\"");

WriteLiteral(" data-bind=\"text: CommonAfeHelper.getReadableDate(CreateDate())\"");

WriteLiteral("></div>\r\n                                </div>\r\n                            </di" +
"v>\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Project Name</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-bind=\"value: ProjectName\"");

WriteLiteral(" />\r\n                                    </div>\r\n                                " +
"</div>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Unit Division</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" class=\"selectpicker\"");

WriteLiteral(" data-bind=\"options: DivisionOptions, optionsText: \'text\', optionsValue: \'value\'," +
" optionsCaption: \'-- Select One --\', selectPicker: DivisionId\"");

WriteLiteral("></select>\r\n                                    </div>\r\n                         " +
"       </div>\r\n                            </div>\r\n                            <" +
"div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Function</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" class=\"selectpicker\"");

WriteLiteral(" data-bind=\"options: FunctionOptions, optionsText: \'text\', optionsValue: \'value\'," +
" optionsCaption: \'-- Select One --\', selectPicker: FunctionId\"");

WriteLiteral("></select>\r\n                                    </div>\r\n                         " +
"       </div>\r\n                            </div>\r\n                            <" +
"div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Site</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" class=\"selectpicker\"");

WriteLiteral(" data-bind=\"options: SiteOptions, optionsText: \'text\', optionsValue: \'value\', opt" +
"ionsCaption: \'-- Select One --\', selectPicker: SiteId\"");

WriteLiteral("></select>\r\n                                    </div>\r\n                         " +
"       </div>\r\n                            </div>\r\n                        </div" +
">\r\n\r\n                        <div");

WriteLiteral(" class=\"row col-md-6\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">AFE Type</label>\r\n                                    <div");

WriteLiteral(" class=\"data-value col-md-8\"");

WriteLiteral(" data-bind=\"text: AfeType\"");

WriteLiteral("></div>\r\n                                </div>\r\n                            </di" +
"v>\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Stage-Gate Project ID</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-bind=\"value: StageGateProjectId\"");

WriteLiteral(" />\r\n                                    </div>\r\n                                " +
"</div>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Reference No</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-bind=\"value: ReferenceNo\"");

WriteLiteral(" />\r\n                                    </div>\r\n                                " +
"</div>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Capital or Revenue</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" id=\"ddlCapitalExpense\"");

WriteLiteral(" class=\"selectpicker\"");

WriteLiteral(" data-bind=\"options: ExpenditureTypeOptions, optionsText: \'text\', optionsValue: \'" +
"value\', optionsCaption: \'-- Select One --\', selectPicker: ExpenditureType\"");

WriteLiteral(@"></select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 2. Classification -->
    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Classification</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row col-md-6\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Nature</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" class=\"selectpicker\"");

WriteLiteral(" data-bind=\"options: NatureOptions, optionsText: \'text\', optionsValue: \'value\', o" +
"ptionsCaption: \'-- Select One --\', selectPicker: NatureId\"");

WriteLiteral("></select>\r\n                                    </div>\r\n                         " +
"       </div>\r\n                            </div>\r\n                        </div" +
">\r\n\r\n                        <div");

WriteLiteral(" class=\"row col-md-6\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Purpose</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" class=\"selectpicker\"");

WriteLiteral(" data-bind=\"options: PurposeOptions, optionsText: \'text\', optionsValue: \'value\', " +
"optionsCaption: \'-- Select One --\', selectPicker: PurposeId\"");

WriteLiteral(@"></select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 3. Description -->
    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Description</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" id=\"txtProjectDescription\"");

WriteLiteral(" rows=\"8\"");

WriteLiteral(" data-bind=\"value: Description\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral("></textarea>\r\n                    </div>\r\n                </div>\r\n            </d" +
"iv>\r\n        </div>\r\n    </div>\r\n\r\n    <!-- 4. Proposal -->\r\n    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Proposal</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" id=\"txtProjectDescription\"");

WriteLiteral(" rows=\"8\"");

WriteLiteral(" data-bind=\"value: Proposal\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral("></textarea>\r\n                    </div>\r\n                </div>\r\n            </d" +
"iv>\r\n        </div>\r\n    </div>\r\n\r\n    <!-- 5. Project Benefits -->\r\n    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Project Benefits</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" id=\"txtProjectDescription\"");

WriteLiteral(" rows=\"8\"");

WriteLiteral(" data-bind=\"value: ProjectBenefits\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral("></textarea>\r\n                    </div>\r\n                </div>\r\n            </d" +
"iv>\r\n        </div>\r\n    </div>\r\n\r\n    <!-- 6. Risks and Control Measures -->\r\n " +
"   <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Risks and Control Measures</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">Project Risks</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtProjectName\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral(" data-bind=\"value: ProjectRisks\"");

WriteLiteral(" />\r\n                                    </div>\r\n                                " +
"</div>\r\n                            </div>\r\n                        </div>\r\n\r\n  " +
"                      <div");

WriteLiteral(" class=\"row col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">Control Measures</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtProjectName\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral(" data-bind=\"value: ControlMeasures\"");

WriteLiteral(@" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 7. Support Documentation -->
    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Supporting Documentation</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">Financial Model</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtProjectName\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral(" ");

WriteLiteral(" />\r\n                                    </div>\r\n                                " +
"</div>\r\n                            </div>\r\n                        </div>\r\n\r\n  " +
"                      <div");

WriteLiteral(" class=\"row col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">Business Case</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtProjectName\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral(" ");

WriteLiteral(" />\r\n                                    </div>\r\n                                " +
"</div>\r\n                            </div>\r\n                        </div>\r\n\r\n  " +
"                      <div");

WriteLiteral(" class=\"row col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">Other Supporting Docs</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtProjectName\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral(" ");

WriteLiteral(@" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 8. Currency & Rate -->
    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Currency & Rate</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row col-md-6\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Currency Code</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" class=\"selectpicker\"");

WriteLiteral(" data-bind=\"options: CurrencyOptions, optionsText: \'text\', optionsValue: \'value\'," +
" optionsCaption: \'-- Select One --\', selectPicker: CurrencyId\"");

WriteLiteral("></select>\r\n                                    </div>\r\n                         " +
"       </div>\r\n                            </div>\r\n                        </div" +
">\r\n\r\n                        <div");

WriteLiteral(" class=\"row col-md-6\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Exchange Rate</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtProjectName\"");

WriteLiteral(" data-bind=\"value: ExchangeRate\"");

WriteLiteral(" />\r\n                                        ");

WriteLiteral(@"
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 9. Financial Information -->
    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Financial Information</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <table");

WriteLiteral(" name=\"afe-costs\"");

WriteLiteral(" class=\"table afe-table\"");

WriteLiteral(">\r\n                            <thead>\r\n                                <tr>\r\n   " +
"                                 <th></th>\r\n                                    " +
"<th");

WriteLiteral(" style=\"width: 250px;\"");

WriteLiteral(">Local Currency Amount</th>\r\n                                    <th");

WriteLiteral(" style=\"width: 250px;\"");

WriteLiteral(">Amount or %</th>\r\n                                    <th");

WriteLiteral(" style=\"width: 50px;\"");

WriteLiteral(@"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1. Estimated Amount Required</td>
                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" class=\"cost\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-bind=\"cost: Amount_LC().Text\"");

WriteLiteral(" style=\"width: 150px;\"");

WriteLiteral(" />\r\n                                    </td>\r\n                                 " +
"   <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"total-cost\"");

WriteLiteral("></div>\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"cost hidden\"");

WriteLiteral(" data-bind=\"totalCost: Amount_USD\"");

WriteLiteral(@" />
                                    </td>
                                    <td>USD</td>
                                </tr>
                                <tr>
                                    <td>2. Budget Item</td>
                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"total-cost\"");

WriteLiteral("></div>\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"cost hidden\"");

WriteLiteral(" data-bind=\"totalCost: Budget_LC\"");

WriteLiteral(" />\r\n                                    </td>\r\n                                 " +
"   <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"total-cost\"");

WriteLiteral("></div>\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"cost hidden\"");

WriteLiteral(" data-bind=\"totalCost: Budget_USD\"");

WriteLiteral(" />\r\n                                    </td>\r\n                                 " +
"   <td>USD</td>\r\n                                </tr>\r\n\r\n                      " +
"          <tr>\r\n                                    <td");

WriteLiteral(" style=\"padding-left: 19px;\"");

WriteLiteral(">2b. Previous AFEs</td>\r\n                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"total-cost\"");

WriteLiteral("></div>\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"cost hidden\"");

WriteLiteral(" data-bind=\"totalCost: PrevAfe_LC\"");

WriteLiteral(" />\r\n                                    </td>\r\n                                 " +
"   <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"total-cost\"");

WriteLiteral("></div>\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"cost hidden\"");

WriteLiteral(" data-bind=\"totalCost: PrevAfe_USD\"");

WriteLiteral(" />\r\n                                    </td>\r\n                                 " +
"   <td>USD</td>\r\n                                </tr>\r\n                        " +
"        <tr");

WriteLiteral(" id=\"tr-remaining-budget\"");

WriteLiteral(" style=\"font-weight: bold;\"");

WriteLiteral(">\r\n                                    <td");

WriteLiteral(" style=\"padding-left: 19px;\"");

WriteLiteral(">2c. Remaining Budget</td>\r\n                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"total-cost\"");

WriteLiteral("></div>\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"cost hidden\"");

WriteLiteral(" data-bind=\"totalCost: RemainingBudget_LC\"");

WriteLiteral(" />\r\n                                    </td>\r\n                                 " +
"   <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"total-cost\"");

WriteLiteral("></div>\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"cost hidden\"");

WriteLiteral(" data-bind=\"totalCost: RemainingBudget_USD\"");

WriteLiteral(@" />
                                    </td>
                                    <td>USD</td>
                                </tr>

                                <tr>
                                    <td>3. i. Cash Payback (before interest)</td>
                                    <td></td>
                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" class=\"month\"");

WriteLiteral(" data-bind=\"value: CashPayback_Before\"");

WriteLiteral(" />\r\n                                    </td>\r\n                                 " +
"   <td>Months</td>\r\n                                </tr>\r\n                     " +
"           <tr>\r\n                                    <td");

WriteLiteral(" style=\"padding-left: 19px;\"");

WriteLiteral(">ii. Cash Payback (after interest)</td>\r\n                                    <td>" +
"</td>\r\n                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" class=\"month\"");

WriteLiteral(" data-bind=\"value: CashPayback_After\"");

WriteLiteral(@" />
                                    </td>
                                    <td>Months</td>
                                </tr>
                                <tr>
                                    <td>4. Average Return on Total Assets (EBIT/Total Assets)</td>
                                    <td></td>
                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"working-interest\"");

WriteLiteral(" data-bind=\"value: AvgReturn\"");

WriteLiteral(@" />
                                    </td>
                                    <td>%</td>
                                </tr>
                                <tr>
                                    <td>5. Net Present Value</td>
                                    <td></td>
                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" class=\"cost\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-bind=\"cost: NPV().Text\"");

WriteLiteral(" style=\"width: 150px;\"");

WriteLiteral(@" />
                                    </td>
                                    <td>USD</td>
                                </tr>
                                <tr>
                                    <td>6. Internal Rate of Return</td>
                                    <td></td>
                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"working-interest\"");

WriteLiteral(" data-bind=\"value: IRR\"");

WriteLiteral(@" />
                                    </td>
                                    <td>%</td>
                                </tr>
                                <tr>
                                    <td>7. Net Write-off on Replaced Assets</td>
                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" class=\"cost\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-bind=\"cost: WriteOff_LC().Text\"");

WriteLiteral(" style=\"width: 150px;\"");

WriteLiteral(" />\r\n                                    </td>\r\n                                 " +
"   <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"total-cost\"");

WriteLiteral("></div>\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"cost hidden\"");

WriteLiteral(" data-bind=\"totalCost: WriteOff_USD\"");

WriteLiteral(@" />
                                    </td>
                                    <td>USD</td>
                                </tr>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                                        <h4>Guidelines</h4>\r\n                 " +
"                       <table");

WriteLiteral(" class=\"table guidelines-table\"");

WriteLiteral(@">
                                            <tr>
                                                <td>Net Present Value</td>
                                                <td>Greater than 0</td>
                                            </tr>
                                            <tr>
                                                <td>Return On Total Assets</td>
                                                <td>15% per annum</td>
                                            </tr>
                                            <tr>
                                                <td>Cash Payback (after interest)</td>
                                                <td>24 months or less is the target.  Greater than 36 months requires special justification.</td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 10. Approvers -->
    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Approvers</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n\r\n                        <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-6 afe-group-outer\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Required Approvers</h5></div>\r\n                                        <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"data-value col-md-12\"");

WriteLiteral(" data-bind=\"foreach: DelegationChain\"");

WriteLiteral(">\r\n                                                        <div");

WriteLiteral(" style=\"padding-bottom: 8px;\"");

WriteLiteral(">\r\n                                                            <span");

WriteLiteral(" data-bind=\"text: Name\"");

WriteLiteral("></span>\r\n                                                            <!-- ko wit" +
"h: Title -->\r\n                                                            - <spa" +
"n");

WriteLiteral(" data-bind=\"text: $data\"");

WriteLiteral(@"></span>
                                                            <!-- /ko -->
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div");

WriteLiteral(" class=\"col-md-6 afe-group-outer\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Additional Requested Approvers</h5></div>\r\n                                 " +
"       <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" data-bind=\"foreach: AdditionalApproverDetails\"");

WriteLiteral(">\r\n                                                <p>\r\n                         " +
"                           <span");

WriteLiteral(" class=\"data-value\"");

WriteLiteral(" data-bind=\"text: Name\"");

WriteLiteral("></span>\r\n                                                    <!-- ko with: Title" +
" -->\r\n                                                    - <span");

WriteLiteral(" data-bind=\"text: $data\"");

WriteLiteral("></span>\r\n                                                    <!-- /ko -->\r\n     " +
"                                               <span");

WriteLiteral(" class=\"btn btn-xs btn-default\"");

WriteLiteral(" style=\"margin-left: 8px;\"");

WriteLiteral(" data-bind=\"click: function(data, event) { $root.removeApprover(data); }\"");

WriteLiteral(">Remove</span>\r\n                                                </p>\r\n           " +
"                                 </div>\r\n                                       " +
"     <div");

WriteLiteral(" id=\"btnRequestAdditionalApproval\"");

WriteLiteral(" class=\"btn btn-default btn-sm\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-plus\"");

WriteLiteral(" style=\"padding-right: 5px;\"");

WriteLiteral(@"></i>Request Additional Approval</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 11. Author Information -->
    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Author Information</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">ACE Request Raised By</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10 data-value\"");

WriteLiteral(" data-bind=\"text: CreatorName\"");

WriteLiteral("></div>\r\n                                </div>\r\n                            </di" +
"v>\r\n                        </div>\r\n                    </div>\r\n                " +
"</div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"margin-bottom: 20px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            ");

WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" style=\"float: right;\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" id=\"btnSaveDraft\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" onclick=\"AfeCaptureFormHelper.SaveDraftAfe()\"");

WriteLiteral(">Save Draft</button>\r\n                    <button");

WriteLiteral(" id=\"btnSubmitAfe\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" onclick=\"AfeCaptureFormHelper.SaveAfe()\"");

WriteLiteral(">Submit</button>\r\n                </div>\r\n            </div>\r\n        </div>\r\n   " +
" </div>\r\n\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"modal-find-user\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" style=\"top: 350px;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"progress-container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n            <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">Find Additional Approver</h4>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"find-user-form\"");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-3\"");

WriteLiteral(">User ID</label>\r\n                    <input");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-bind=\"value: Search.Id\"");

WriteLiteral(" />\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-3\"");

WriteLiteral(">First Name</label>\r\n                    <input");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-bind=\"value: Search.Firstname\"");

WriteLiteral(" />\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-3\"");

WriteLiteral(">Last Name</label>\r\n                    <input");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-bind=\"value: Search.Lastname\"");

WriteLiteral(" />\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-3\"");

WriteLiteral(">Email</label>\r\n                    <input");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(" type=\"email\"");

WriteLiteral(" data-bind=\"value: Search.Email\"");

WriteLiteral(" />\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"control-label col-md-3\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" id=\"btnFindUser\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">Find User</button>\r\n                    </div>\r\n                    <div");

WriteLiteral(" id=\"find-user-warning\"");

WriteLiteral(" class=\"col-md-9 text-danger collapse\"");

WriteLiteral(" style=\"padding-top: 9px;\"");

WriteLiteral(">\r\n                        <p");

WriteLiteral(" style=\"margin-left: -15px;\"");

WriteLiteral(@">
                            Please provide at least one of the following:
                            <ul>
                                <li>NT ID</li>
                                <li>First Name</li>
                                <li>Last Name</li>
                                <li>Email</li>
                            </ul>
                        </p>
                    </div>
                </div>
            </div>
            <div");

WriteLiteral(" id=\"divFindUserResults\"");

WriteLiteral(" class=\"collapse\"");

WriteLiteral(" style=\"max-height: 150px; overflow-y: auto;\"");

WriteLiteral(" data-bind=\"foreach: SearchResults\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"radio\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"find-user-results\"");

WriteLiteral(" data-bind=\"value: FlexIdentifier, attr: { id: \'user-\' + Id }\"");

WriteLiteral(" />\r\n                    <label");

WriteLiteral(" data-bind=\"attr: { for: \'user-\' + Id }\"");

WriteLiteral("><span");

WriteLiteral(" data-bind=\"text: Name\"");

WriteLiteral("></span> | <span");

WriteLiteral(" data-bind=\"text: Id\"");

WriteLiteral("></span> | <span");

WriteLiteral(" data-bind=\"text: Email\"");

WriteLiteral("></span></label>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"divNoResults\"");

WriteLiteral(" class=\"collapse\"");

WriteLiteral(">No users found.</div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Cancel</button>\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnSaveUser\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" disabled>Save</button>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"find-user-progress\"");

WriteLiteral(" class=\"flex-update-progress collapse\"");

WriteLiteral(" data-container-id=\"progress-container\"");

WriteLiteral("><div");

WriteLiteral(" class=\"loader\"");

WriteLiteral("></div></div>\r\n\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"afe-capture-progress\"");

WriteLiteral(" class=\"flex-update-progress collapse\"");

WriteLiteral(" data-container-id=\"afe-capture-container\"");

WriteLiteral("><div");

WriteLiteral(" class=\"loader\"");

WriteLiteral("></div></div>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $().ready(function () {\r\n        var isSupplement = false;\r\n");

            
            #line 614 "..\..\Views\AfeCapture\Form.cshtml"
        
            
            #line default
            #line hidden
            
            #line 614 "..\..\Views\AfeCapture\Form.cshtml"
         if (@Model.IsSupplement) {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("isSupplement = true;");

WriteLiteral("\r\n");

            
            #line 616 "..\..\Views\AfeCapture\Form.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        AfeCaptureFormHelper.InitializeViewModel(isSupplement, \'");

            
            #line 618 "..\..\Views\AfeCapture\Form.cshtml"
                                                           Write(Model.AfeCreateType);

            
            #line default
            #line hidden
WriteLiteral("\', +\'");

            
            #line 618 "..\..\Views\AfeCapture\Form.cshtml"
                                                                                    Write(Model.AfeId);

            
            #line default
            #line hidden
WriteLiteral("\', \'");

            
            #line 618 "..\..\Views\AfeCapture\Form.cshtml"
                                                                                                    Write(Model.CreatorName);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n    });\r\n</script>");

        }
    }
}
#pragma warning restore 1591
