#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Aci.Flex.Plugins.AnsellAfe.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/AfeCapture/Index.cshtml")]
    public partial class _Views_AfeCapture_Index_cshtml : System.Web.Mvc.WebViewPage<Aci.Flex.Plugins.AnsellAfe.Web.Models.AfeInitializationData>
    {
        public _Views_AfeCapture_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\AfeCapture\Index.cshtml"
  
    Layout = "~/Views/Shared/_AfeLayout.cshtml";
#if DEBUG
        ;

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 157), Tuple.Create("\"", 202)
            
            #line 7 "..\..\Views\AfeCapture\Index.cshtml"
, Tuple.Create(Tuple.Create("", 163), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/Enum.js?v=1.0")
            
            #line default
            #line hidden
, 163), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 226), Tuple.Create("\"", 284)
            
            #line 8 "..\..\Views\AfeCapture\Index.cshtml"
, Tuple.Create(Tuple.Create("", 232), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/TypeScriptClasses.js?v=1.0")
            
            #line default
            #line hidden
, 232), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 308), Tuple.Create("\"", 362)
            
            #line 9 "..\..\Views\AfeCapture\Index.cshtml"
, Tuple.Create(Tuple.Create("", 314), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/common-helper.js?v=1.0")
            
            #line default
            #line hidden
, 314), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 386), Tuple.Create("\"", 449)
            
            #line 10 "..\..\Views\AfeCapture\Index.cshtml"
, Tuple.Create(Tuple.Create("", 392), Tuple.Create<System.Object, System.Int32>(Url.Content("~/CodeGen/CommonAfeApiController.js?v=1.0")
            
            #line default
            #line hidden
, 392), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 473), Tuple.Create("\"", 540)
            
            #line 11 "..\..\Views\AfeCapture\Index.cshtml"
, Tuple.Create(Tuple.Create("", 479), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/AfeCapture/afecapture-form.js?v=1.0")
            
            #line default
            #line hidden
, 479), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 564), Tuple.Create("\"", 615)
            
            #line 12 "..\..\Views\AfeCapture\Index.cshtml"
, Tuple.Create(Tuple.Create("", 570), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/money-view.js?v=1.0")
            
            #line default
            #line hidden
, 570), false)
);

WriteLiteral("></script>\r\n");

            
            #line 13 "..\..\Views\AfeCapture\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\AfeCapture\Index.cshtml"
                                                                                       

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 728), Tuple.Create("\"", 787)
            
            #line 14 "..\..\Views\AfeCapture\Index.cshtml"
, Tuple.Create(Tuple.Create("", 734), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/select-list-helper.js?v=1.0")
            
            #line default
            #line hidden
, 734), false)
);

WriteLiteral("></script>\r\n");

            
            #line 15 "..\..\Views\AfeCapture\Index.cshtml"
#else
    ;

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 825), Tuple.Create("\"", 919)
            
            #line 17 "..\..\Views\AfeCapture\Index.cshtml"
, Tuple.Create(Tuple.Create("", 831), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/Scripts/Aci.Flex.Plugins.AnsellAfe.Web.Scripts.Enum.js?v=1.0")
            
            #line default
            #line hidden
, 831), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 943), Tuple.Create("\"", 1050)
            
            #line 18 "..\..\Views\AfeCapture\Index.cshtml"
, Tuple.Create(Tuple.Create("", 949), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/Scripts/Aci.Flex.Plugins.AnsellAfe.Web.Scripts.TypeScriptClasses.js?v=1.0")
            
            #line default
            #line hidden
, 949), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1074), Tuple.Create("\"", 1177)
            
            #line 19 "..\..\Views\AfeCapture\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1080), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/Scripts/Aci.Flex.Plugins.AnsellAfe.Web.Scripts.common-helper.js?v=1.0")
            
            #line default
            #line hidden
, 1080), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1201), Tuple.Create("\"", 1313)
            
            #line 20 "..\..\Views\AfeCapture\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1207), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/CodeGen/Aci.Flex.Plugins.AnsellAfe.Web.CodeGen.CommonAfeApiController.js?v=1.0")
            
            #line default
            #line hidden
, 1207), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1337), Tuple.Create("\"", 1453)
            
            #line 21 "..\..\Views\AfeCapture\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1343), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/Scripts/Aci.Flex.Plugins.AnsellAfe.Web.Scripts.AfeCapture.afecapture-form.js?v=1.0")
            
            #line default
            #line hidden
, 1343), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1477), Tuple.Create("\"", 1577)
            
            #line 22 "..\..\Views\AfeCapture\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1483), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/Scripts/Aci.Flex.Plugins.AnsellAfe.Web.Scripts.money-view.js?v=1.0")
            
            #line default
            #line hidden
, 1483), false)
);

WriteLiteral("></script>\r\n");

            
            #line 23 "..\..\Views\AfeCapture\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\AfeCapture\Index.cshtml"
                                                                                                                                        

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1739), Tuple.Create("\"", 1847)
            
            #line 24 "..\..\Views\AfeCapture\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1745), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/Scripts/Aci.Flex.Plugins.AnsellAfe.Web.Scripts.select-list-helper.js?v=1.0")
            
            #line default
            #line hidden
, 1745), false)
);

WriteLiteral("></script>\r\n");

            
            #line 25 "..\..\Views\AfeCapture\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\AfeCapture\Index.cshtml"
Write(Scripts.Render("~/bundles/wysiwyg"));

            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\AfeCapture\Index.cshtml"
                                        
#endif

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"afe-capture-container\"");

WriteLiteral(">\r\n\r\n    <!-- 1. ACE Request Information -->\r\n    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>ACE Request Information</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row col-md-6\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Creation Date</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"data-value col-md-8\"");

WriteLiteral(" data-bind=\"text: CommonAfeHelper.getReadableDate(CreateDate())\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"    </div>\r\n                            </div>\r\n                            <div" +
"");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Unit Division</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" class=\"selectpicker\"");

WriteLiteral(" data-bind=\"options: DivisionOptions, optionsText: \'text\', optionsValue: \'value\'," +
" optionsCaption: \'-- Select One --\', selectPicker: DivisionId\"");

WriteLiteral("></select>\r\n                                    </div>\r\n                         " +
"       </div>\r\n                            </div>\r\n                            <" +
"div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Function</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" class=\"selectpicker\"");

WriteLiteral(" data-bind=\"options: FunctionOptions, optionsText: \'text\', optionsValue: \'value\'," +
" optionsCaption: \'-- Select One --\', selectPicker: FunctionId\"");

WriteLiteral("></select>\r\n                                    </div>\r\n                         " +
"       </div>\r\n                            </div>\r\n                            <" +
"div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Site</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" class=\"selectpicker\"");

WriteLiteral(" data-bind=\"options: SiteOptions, optionsText: \'text\', optionsValue: \'value\', opt" +
"ionsCaption: \'-- Select One --\', selectPicker: SiteId\"");

WriteLiteral("></select>\r\n                                    </div>\r\n                         " +
"       </div>\r\n                            </div>\r\n                            <" +
"div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Capital or Revenue</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" id=\"ddlCapitalExpense\"");

WriteLiteral(" class=\"selectpicker\"");

WriteLiteral(" data-bind=\"options: ExpenditureTypeOptions, optionsText: \'text\', optionsValue: \'" +
"value\', optionsCaption: \'-- Select One --\', selectPicker: ExpenditureType\"");

WriteLiteral("></select>\r\n                                    </div>\r\n                         " +
"       </div>\r\n                            </div>\r\n                        </div" +
">\r\n\r\n                        <div");

WriteLiteral(" class=\"row col-md-6\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Stage-Gate Project ID</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtProjectName\"");

WriteLiteral(" ");

WriteLiteral(" />\r\n                                    </div>\r\n                                " +
"</div>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Reference No</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtProjectName\"");

WriteLiteral(" ");

WriteLiteral(@" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 2. Classification -->
    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Classification</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row col-md-6\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Nature</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" class=\"selectpicker\"");

WriteLiteral(" data-bind=\"options: NatureOptions, optionsText: \'text\', optionsValue: \'value\', o" +
"ptionsCaption: \'-- Select One --\', selectPicker: NatureId\"");

WriteLiteral("></select>\r\n                                    </div>\r\n                         " +
"       </div>\r\n                            </div>\r\n                        </div" +
">\r\n\r\n                        <div");

WriteLiteral(" class=\"row col-md-6\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Purpose</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" class=\"selectpicker\"");

WriteLiteral(" data-bind=\"options: PurposeOptions, optionsText: \'text\', optionsValue: \'value\', " +
"optionsCaption: \'-- Select One --\', selectPicker: PurposeId\"");

WriteLiteral(@"></select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 3. Description -->
    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Description</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" id=\"txtProjectDescription\"");

WriteLiteral(" rows=\"8\"");

WriteLiteral(" ");

WriteLiteral(" style=\"width: 100%;\"></textarea>\r\n                    </div>\r\n                </" +
"div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <!-- 4. Proposal -->" +
"\r\n    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Proposal</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" id=\"txtProjectDescription\"");

WriteLiteral(" rows=\"8\"");

WriteLiteral(" ");

WriteLiteral(" style=\"width: 100%;\"></textarea>\r\n                    </div>\r\n                </" +
"div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <!-- 5. Project Bene" +
"fits -->\r\n    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Project Benefits</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" id=\"txtProjectDescription\"");

WriteLiteral(" rows=\"8\"");

WriteLiteral(" ");

WriteLiteral(" style=\"width: 100%;\"></textarea>\r\n                    </div>\r\n                </" +
"div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <!-- 6. Risks and Co" +
"ntrol Measures -->\r\n    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Risks and Control Measures</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">Project Risks</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtProjectName\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral(" ");

WriteLiteral(" />\r\n                                    </div>\r\n                                " +
"</div>\r\n                            </div>\r\n                        </div>\r\n\r\n  " +
"                      <div");

WriteLiteral(" class=\"row col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">Control Measures</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtProjectName\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral(" ");

WriteLiteral(@" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 7. Support Documentation -->
    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Supporting Documentation</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">Financial Model</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtProjectName\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral(" ");

WriteLiteral(" />\r\n                                    </div>\r\n                                " +
"</div>\r\n                            </div>\r\n                        </div>\r\n\r\n  " +
"                      <div");

WriteLiteral(" class=\"row col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">Business Case</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtProjectName\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral(" ");

WriteLiteral(" />\r\n                                    </div>\r\n                                " +
"</div>\r\n                            </div>\r\n                        </div>\r\n\r\n  " +
"                      <div");

WriteLiteral(" class=\"row col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">Other Supporting Docs</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtProjectName\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral(" ");

WriteLiteral(@" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 8. Currency & Rate -->
    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Currency & Rate</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row col-md-6\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Currency Code</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" class=\"selectpicker\"");

WriteLiteral(" data-bind=\"options: CurrencyOptions, optionsText: \'text\', optionsValue: \'value\'," +
" optionsCaption: \'-- Select One --\', selectPicker: CurrencyId\"");

WriteLiteral("></select>\r\n                                    </div>\r\n                         " +
"       </div>\r\n                            </div>\r\n                        </div" +
">\r\n\r\n                        <div");

WriteLiteral(" class=\"row col-md-6\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Exchange Rate</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtProjectName\"");

WriteLiteral(" data-bind=\"value: ExchangeRate\"");

WriteLiteral(" />\r\n                                        ");

WriteLiteral(@"
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 9. Financial Information -->
    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Financial Information</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <table");

WriteLiteral(" name=\"afe-costs\"");

WriteLiteral(" class=\"table afe-table\"");

WriteLiteral(">\r\n                            <thead>\r\n                                <tr>\r\n   " +
"                                 <th></th>\r\n                                    " +
"<th");

WriteLiteral(" style=\"width: 250px;\"");

WriteLiteral(">Local Currency Amount</th>\r\n                                    <th");

WriteLiteral(" style=\"width: 250px;\"");

WriteLiteral(">Amount or %</th>\r\n                                    <th");

WriteLiteral(" style=\"width: 50px;\"");

WriteLiteral(@"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1. Estimated Amount Required</td>
                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" class=\"cost\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-bind=\"cost: Amount_LC().Text\"");

WriteLiteral(" style=\"width: 150px;\"");

WriteLiteral(" />\r\n                                    </td>\r\n                                 " +
"   <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"total-cost\"");

WriteLiteral("></div>\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"cost hidden\"");

WriteLiteral(" data-bind=\"totalCost: Amount_USD\"");

WriteLiteral(@" />
                                    </td>
                                    <td>USD</td>
                                </tr>
                                <tr>
                                    <td>2. Budget Item</td>
                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" class=\"cost\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-bind=\"cost: Budget_LC().Text\"");

WriteLiteral(" style=\"width: 150px;\"");

WriteLiteral(" />\r\n                                    </td>\r\n                                 " +
"   <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"total-cost\"");

WriteLiteral("></div>\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"cost hidden\"");

WriteLiteral(" data-bind=\"totalCost: Budget_USD\"");

WriteLiteral(@" />
                                    </td>
                                    <td>USD</td>
                                </tr>
                                <tr>
                                    <td>3. i. Cash Payback (before interest)</td>
                                    <td></td>
                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" class=\"month\"");

WriteLiteral(" data-bind=\"value: CashPayback_Before\"");

WriteLiteral(" />\r\n                                    </td>\r\n                                 " +
"   <td>Months</td>\r\n                                </tr>\r\n                     " +
"           <tr>\r\n                                    <td");

WriteLiteral(" style=\"padding-left: 10px;\"");

WriteLiteral(">ii. Cash Payback (after interest)</td>\r\n                                    <td>" +
"</td>\r\n                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" class=\"month\"");

WriteLiteral(" data-bind=\"value: CashPayback_After\"");

WriteLiteral(@" />
                                    </td>
                                    <td>Months</td>
                                </tr>
                                <tr>
                                    <td>4. Average Return on Total Assets (EBIT/Total Assets)</td>
                                    <td></td>
                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"working-interest\"");

WriteLiteral(" data-bind=\"value: AvgReturn\"");

WriteLiteral(@" />
                                    </td>
                                    <td>%</td>
                                </tr>
                                <tr>
                                    <td>5. Net Present Value</td>
                                    <td></td>
                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" class=\"cost\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-bind=\"cost: NPV().Text\"");

WriteLiteral(" style=\"width: 150px;\"");

WriteLiteral(@" />
                                    </td>
                                    <td>USD</td>
                                </tr>
                                <tr>
                                    <td>6. Internal Rate of Return</td>
                                    <td></td>
                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"working-interest\"");

WriteLiteral(" data-bind=\"value: IRR\"");

WriteLiteral(@" />
                                    </td>
                                    <td>%</td>
                                </tr>
                                <tr>
                                    <td>7. Net Write-off on Replaced Assets</td>
                                    <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" class=\"cost\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-bind=\"cost: WriteOff_LC().Text\"");

WriteLiteral(" style=\"width: 150px;\"");

WriteLiteral(" />\r\n                                    </td>\r\n                                 " +
"   <td");

WriteLiteral(" class=\"afe-financial-data-entry\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"total-cost\"");

WriteLiteral("></div>\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"cost hidden\"");

WriteLiteral(" data-bind=\"totalCost: WriteOff_USD\"");

WriteLiteral(@" />
                                    </td>
                                    <td>USD</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 10. Approvers -->
    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Approvers</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n\r\n                    </div>\r\n                </div>\r\n            </div>\r\n    " +
"    </div>\r\n    </div>\r\n\r\n    <!-- 11. Author Information -->\r\n    <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Author Information</h5></div>\r\n                    <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">ACE Request Raised By</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10 data-value\"");

WriteLiteral(" data-bind=\"text: CreatorName\"");

WriteLiteral("></div>\r\n                                </div>\r\n                            </di" +
"v>\r\n                        </div>\r\n                    </div>\r\n                " +
"</div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"afe-capture-progress\"");

WriteLiteral(" class=\"flex-update-progress collapse\"");

WriteLiteral(" data-container-id=\"afe-capture-container\"");

WriteLiteral("><div");

WriteLiteral(" class=\"loader\"");

WriteLiteral("></div></div>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $().ready(function () {\r\n        var isSupplement = false;\r\n");

            
            #line 434 "..\..\Views\AfeCapture\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 434 "..\..\Views\AfeCapture\Index.cshtml"
         if (@Model.IsSupplement) {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("isSupplement = true;");

WriteLiteral("\r\n");

            
            #line 436 "..\..\Views\AfeCapture\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        AfeCaptureFormHelper.InitializeViewModel(isSupplement, \'");

            
            #line 438 "..\..\Views\AfeCapture\Index.cshtml"
                                                           Write(Model.AfeCreateType);

            
            #line default
            #line hidden
WriteLiteral("\', +\'");

            
            #line 438 "..\..\Views\AfeCapture\Index.cshtml"
                                                                                    Write(Model.AfeId);

            
            #line default
            #line hidden
WriteLiteral("\', \'");

            
            #line 438 "..\..\Views\AfeCapture\Index.cshtml"
                                                                                                    Write(Model.CreatorName);

            
            #line default
            #line hidden
WriteLiteral(@"');
    });

    // Could not find a way to put this is a TypeScript due to typing issues.
    //ko.bindingHandlers['wysiwyg'].defaults = {
    //    plugins: [
    //        ""advlist autolink link charmap"",
    //        ""searchreplace visualblocks code"",
    //        ""insertdatetime media table contextmenu paste""
    //    ],
    //    menubar: ""edit view format table tools"",
    //    toolbar: ""insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | link"",
    //    remove_linebreaks: false,
    //    force_p_newlines: false,
    //    force_br_newlines: true,
    //    forced_root_block: '<div>'
    //};
</script>");

        }
    }
}
#pragma warning restore 1591
