#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Aci.Flex.Plugins.AnsellAfe.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/AfeCapture/Options.cshtml")]
    public partial class _Views_AfeCapture_Options_cshtml : System.Web.Mvc.WebViewPage<Aci.Flex.Plugins.AnsellAfe.Web.Models.AfeCaptureFormOptions>
    {
        public _Views_AfeCapture_Options_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\AfeCapture\Options.cshtml"
  
    Layout = "~/Views/Shared/_AfeLayout.cshtml";
#if DEBUG
        ;

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 157), Tuple.Create("\"", 227)
            
            #line 7 "..\..\Views\AfeCapture\Options.cshtml"
, Tuple.Create(Tuple.Create("", 163), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/AfeCapture/afecapture-options.js?v=1.0")
            
            #line default
            #line hidden
, 163), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 251), Tuple.Create("\"", 301)
            
            #line 8 "..\..\Views\AfeCapture\Options.cshtml"
, Tuple.Create(Tuple.Create("", 257), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/validator.js?v=1.0")
            
            #line default
            #line hidden
, 257), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 325), Tuple.Create("\"", 388)
            
            #line 9 "..\..\Views\AfeCapture\Options.cshtml"
, Tuple.Create(Tuple.Create("", 331), Tuple.Create<System.Object, System.Int32>(Url.Content("~/CodeGen/CommonAfeApiController.js?v=1.0")
            
            #line default
            #line hidden
, 331), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 412), Tuple.Create("\"", 470)
            
            #line 10 "..\..\Views\AfeCapture\Options.cshtml"
, Tuple.Create(Tuple.Create("", 418), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/TypeScriptClasses.js?v=1.0")
            
            #line default
            #line hidden
, 418), false)
);

WriteLiteral("></script>\r\n");

            
            #line 11 "..\..\Views\AfeCapture\Options.cshtml"
#else
    ;

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 508), Tuple.Create("\"", 627)
            
            #line 13 "..\..\Views\AfeCapture\Options.cshtml"
, Tuple.Create(Tuple.Create("", 514), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/Scripts/Aci.Flex.Plugins.AnsellAfe.Web.Scripts.AfeCapture.afecapture-options.js?v=1.0")
            
            #line default
            #line hidden
, 514), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 651), Tuple.Create("\"", 750)
            
            #line 14 "..\..\Views\AfeCapture\Options.cshtml"
, Tuple.Create(Tuple.Create("", 657), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/Scripts/Aci.Flex.Plugins.AnsellAfe.Web.Scripts.validator.js?v=1.0")
            
            #line default
            #line hidden
, 657), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 774), Tuple.Create("\"", 886)
            
            #line 15 "..\..\Views\AfeCapture\Options.cshtml"
, Tuple.Create(Tuple.Create("", 780), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/CodeGen/Aci.Flex.Plugins.AnsellAfe.Web.CodeGen.CommonAfeApiController.js?v=1.0")
            
            #line default
            #line hidden
, 780), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 910), Tuple.Create("\"", 1017)
            
            #line 16 "..\..\Views\AfeCapture\Options.cshtml"
, Tuple.Create(Tuple.Create("", 916), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/Scripts/Aci.Flex.Plugins.AnsellAfe.Web.Scripts.TypeScriptClasses.js?v=1.0")
            
            #line default
            #line hidden
, 916), false)
);

WriteLiteral("></script>\r\n");

            
            #line 17 "..\..\Views\AfeCapture\Options.cshtml"
#endif

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"action-nav-normal\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"action-nav-row action-nav-line row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-4 action-nav-button\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\'", 1194), Tuple.Create("\'", 1233)
            
            #line 23 "..\..\Views\AfeCapture\Options.cshtml"
, Tuple.Create(Tuple.Create("", 1201), Tuple.Create<System.Object, System.Int32>(Url.Action("New", "AfeCapture")
            
            #line default
            #line hidden
, 1201), false)
);

WriteLiteral(" title=\"Create New AFE\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-file-text-o fa-4x\"");

WriteLiteral("></i>\r\n                <span>Create New AFE</span>\r\n            </a>\r\n        </d" +
"iv>\r\n        <div");

WriteLiteral(" class=\"col-sm-4 action-nav-button\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" onclick=\"AfeCaptureOptions.ShowOptions(\'clone\')\"");

WriteLiteral(" title=\"Clone Existing AFE\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-files-o fa-4x\"");

WriteLiteral("></i>\r\n                <span>Clone Existing AFE</span>\r\n            </a>\r\n       " +
" </div>\r\n        <div");

WriteLiteral(" class=\"col-sm-4 action-nav-button\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" onclick=\"AfeCaptureOptions.ShowOptions(\'supplement\')\"");

WriteLiteral(" title=\"Create Supplement AFE\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-clipboard fa-4x\"");

WriteLiteral("></i>\r\n                <span>Create Supplement AFE</span>\r\n            </a>\r\n    " +
"    </div>\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"modal-options\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" style=\"top: 200px;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n        <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral("><span");

WriteLiteral(" id=\"options-header\"");

WriteLiteral("></span></h4>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"modal-body form-horizontal\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"search-afe\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-md-5 control-label\"");

WriteLiteral(">Search for AFE</label>\r\n                <div");

WriteLiteral(" class=\"col-md-7\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtSearch\"");

WriteLiteral(" name=\"txtSearch\"");

WriteLiteral(" placeholder=\"AFE Number | AFE ID | Project Name\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral("\r\n                           data-bv-notempty");

WriteLiteral(" data-bv-notempty-message=\"Search term is required.\"");

WriteLiteral(" data-bv-trigger=\"keyup\"");

WriteLiteral(" data-bind=\"value: query\"");

WriteLiteral(" />\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-7 col-md-offset-5\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnSearch\"");

WriteLiteral(" class=\"btn btn-default btn-sm\"");

WriteLiteral(" onclick=\"AfeCaptureOptions.SearchAfe()\"");

WriteLiteral(" disabled>Search</button>\r\n                    <img");

WriteLiteral(" id=\"search-indicator\"");

WriteAttribute("src", Tuple.Create(" src=\'", 3055), Tuple.Create("\'", 3096)
            
            #line 59 "..\..\Views\AfeCapture\Options.cshtml"
, Tuple.Create(Tuple.Create("", 3061), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Images/loader.gif")
            
            #line default
            #line hidden
, 3061), false)
);

WriteLiteral(" class=\"collapse\"");

WriteLiteral(" style=\"padding-left: 10px;\"");

WriteLiteral(" />\r\n                </div>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" id=\"afe-results\"");

WriteLiteral(" class=\"collapsed\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"col-md-5 control-label\"");

WriteLiteral(">AFE Search Results</label>\r\n                    <div");

WriteLiteral(" class=\"col-md-7\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" style=\"max-height: 150px; overflow-y: auto;\"");

WriteLiteral(" data-bind=\"foreach: foundAfes\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"radio\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 69 "..\..\Views\AfeCapture\Options.cshtml"
                           Write(Html.RadioButtonFor(m => m.SelectedAfeId, string.Empty, new { data_bind = "value: AfeId, attr: { id: 'afe-' + AfeId() }" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <label");

WriteLiteral(" data-bind=\"text: ProjectName(), attr: { for: \'afe-\' + AfeId() }\"");

WriteLiteral("></label>\r\n                            </div>\r\n                        </div>\r\n  " +
"                      <div");

WriteLiteral(" id=\"no-afes\"");

WriteLiteral(" data-bind=\"visible: foundAfes().length == 0\"");

WriteLiteral(" style=\"padding-top: 7px;\"");

WriteLiteral(">No AFEs found.</div>\r\n                    </div>\r\n                </div>\r\n      " +
"      </div>\r\n        </div>\r\n\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Cancel</button>\r\n        <button");

WriteLiteral(" id=\"btn-option-submit\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" onclick=\"AfeCaptureOptions.SubmitAfeOptions()\"");

WriteLiteral("></button>\r\n    </div>\r\n</div>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $().ready(function () {\r\n        AfeCaptureOptions.InitializeOptions();\r\n " +
"   });\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
