#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Aci.Flex.Plugins.AnsellAfe.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Workflow/Recall.cshtml")]
    public partial class _Views_Workflow_Recall_cshtml : System.Web.Mvc.WebViewPage<Aci.Flex.Server.Workflow.FlexActivityMetadata>
    {
        public _Views_Workflow_Recall_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Workflow\Recall.cshtml"
  
    Layout = "~/Views/Shared/_AfeLayout.cshtml";
#if DEBUG
        ;

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 147), Tuple.Create("\"", 200)
            
            #line 7 "..\..\Views\Workflow\Recall.cshtml"
, Tuple.Create(Tuple.Create("", 153), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/recall-afe.js?v=1.0.1")
            
            #line default
            #line hidden
, 153), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 228), Tuple.Create("\"", 291)
            
            #line 8 "..\..\Views\Workflow\Recall.cshtml"
, Tuple.Create(Tuple.Create("", 234), Tuple.Create<System.Object, System.Int32>(Url.Content("~/CodeGen/CommonAfeApiController.js?v=1.0")
            
            #line default
            #line hidden
, 234), false)
);

WriteLiteral("></script>\r\n");

            
            #line 9 "..\..\Views\Workflow\Recall.cshtml"
#else
    ;

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 333), Tuple.Create("\"", 433)
            
            #line 11 "..\..\Views\Workflow\Recall.cshtml"
, Tuple.Create(Tuple.Create("", 339), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/Scripts/Aci.Flex.Plugins.AnsellAfe.Web.Scripts.recall-afe.js?v=1.0")
            
            #line default
            #line hidden
, 339), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 461), Tuple.Create("\"", 573)
            
            #line 12 "..\..\Views\Workflow\Recall.cshtml"
, Tuple.Create(Tuple.Create("", 467), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Resources/CodeGen/Aci.Flex.Plugins.AnsellAfe.Web.CodeGen.CommonAfeApiController.js?v=1.0")
            
            #line default
            #line hidden
, 467), false)
);

WriteLiteral("></script>\r\n");

            
            #line 13 "..\..\Views\Workflow\Recall.cshtml"
#endif
    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" id=\"binding-container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"recall-modal\"");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"row afe-group-row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-12 afe-group-outer\"");

WriteLiteral(" style=\"margin-top: 20px;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-12 afe-group no-padding\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral("><h5>Comments<span");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(" style=\"font-size: 0.8em; padding-left: 8px;\"");

WriteLiteral(">*</span></h5></div>\r\n                            <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                                <textarea");

WriteLiteral(" id=\"txtComments\"");

WriteLiteral(" rows=\"8\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral(" data-bind=\"value: Comments\"");

WriteLiteral("></textarea>\r\n                            </div>\r\n                        </div>\r" +
"\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
" </div>\r\n\r\n        <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" style=\"float: right;\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Cancel</button>\r\n                        <button");

WriteLiteral(" id=\"btnRetract\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(" onclick=\"RecallAfeHelper.Recall()\"");

WriteLiteral(">Recall</button>\r\n                    </div>\r\n                </div>\r\n           " +
" </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" id=\"recall-progress\"");

WriteLiteral(" class=\"flex-update-progress collapse\"");

WriteLiteral(" data-container-id=\"binding-container\"");

WriteLiteral("><div");

WriteLiteral(" class=\"loader\"");

WriteLiteral("></div></div>\r\n\r\n    </div>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        RecallAfeHelper.Initialize(\'");

            
            #line 49 "..\..\Views\Workflow\Recall.cshtml"
                               Write(Model.WorkflowInstanceId);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n    </script>");

        }
    }
}
#pragma warning restore 1591
